### PR TITLE
Remove IFD usage

### PR DESCRIPTION
**Pull request by SuperSandro2000**

### CODE REVIEW

**Comment by Gabriella439** [comment]
What's the motivation for removing the IFD?  Usually I'd prefer to keep it so that I don't have to manually update the derivation when the version or dependencies change

**Comment by SuperSandro2000** [comment]
I am just copying what I wrote for nom since the same applies here https://github.com/maralorn/nix-output-monitor/issues/57#issuecomment-1438772827

> Using IFD and hydra is a really bad combination. The hydra evaluator basically builds the IFD input at eval time which can take a few hours when cache is missing after a staging-next merge and for example gcc.arch/gcc.tune are set.

**Comment by Gabriella439** [comment]
Nixpkgs isn't depending on this repo as a flake, though, as far as I know.  I thought if Nixpkgs were to incorporate `nix-diff` it would be in the usual way as part of `hackage-packages.nix`

**Comment by SuperSandro2000** [comment]
Yes, nixpkgs does not allow IFD, this is about when people include the flake in their config and then build that on a hydra.

**Comment by Gabriella439** [comment]
I'd still prefer to avoid manually maintaining the `nix-diff.nix` file.

Given how small the `flake.nix` logic is, a downstream user that needed to build this repo on `hydra` could still easily author and maintain their own `flake.nix` that doesn't use import from derivation.

**Comment by SuperSandro2000** [comment]
> Given how small the `flake.nix` logic is, a downstream user that needed to build this repo on `hydra` could still easily author and maintain their own `flake.nix` that doesn't use import from derivation.

That's a pretty inconvenient solution that generates a whole bunch of overhead. 

> I'd still prefer to avoid manually maintaining the `nix-diff.nix` file.

It could be auto commited by github actions.

**Comment by sorki** [comment]
> > Given how small the `flake.nix` logic is, a downstream user that needed to build this repo on `hydra` could still easily author and maintain their own `flake.nix` that doesn't use import from derivation.
> 
> That's a pretty inconvenient solution that generates a whole bunch of overhead.
> 
> > I'd still prefer to avoid manually maintaining the `nix-diff.nix` file.
> 
> It could be auto commited by github actions.

That would also create additional overhead, complexity, commits and required another GH action. Also, the same holds for downstream flake that could be auto-generated and auto-commited for Hydra consumption. 

Or simply enable IFD on your Hydra.

**Comment by SuperSandro2000** [comment]
> Or simply enable IFD on your Hydra.

This is not as simple as you think. If hydra for whatever reason starts to compile ghc or anything really deeply into haskell, so for short more than just nix-diff, then the entire log of everything that is being is put into the evaluation tab. This can easily be a 20 MBs at which point the jobset overview gets incredible resource hungry and crashes your browser because hydra website loads the log of the evaluation tab even when not visited and tries to display it.

**Comment by sorki** [comment]
> > Or simply enable IFD on your Hydra.
> 
> This is not as simple as you think. If hydra for whatever reason starts to compile ghc or anything really deeply into haskell, so for short more than just nix-diff, then the entire log of everything that is being is put into the evaluation tab. This can easily be a 20 MBs at which point the jobset overview gets incredible resource hungry and crashes your browser because hydra website loads the log of the evaluation tab even when not visited and tries to display it.

Well then this is a Hydra issue, closing :upside_down_face:

**Comment by SuperSandro2000** [comment]
😮‍💨

**Pull request closed without merging**
