### PR TITLE
Implement heuristic inputDrvs matching

### PR DESCRIPTION
**Pull request by andreabedini**
Sometimes I have to deal with derivations obtained with `pkgs.releaseTools.aggregate`. In my case these derivations have many inputs which include the same packages compiled in different forms, e.g. Haskell packages compiled for different combinations of platform and compiler versions. The derivations are named according to the Haskell package name, so the derivation name alone is not enough to identify which platform and compiler version are used.

In this scenario, nix-diff struggles because it cannot match multiple input derivations with the same name:
```
• The set of input derivations named `cardano-node-8.1.1-linux` do not match
    - /nix/store/cfsp91563mmi6yvz8fcvmgw1nks4dqsa-cardano-node-8.1.1-linux.drv:{out}
    - /nix/store/nvxxaynf8yw1r33j9jvl2nhsv2f9a59w-cardano-node-8.1.1-linux.drv:{out}
    + /nix/store/39k310w52vzx6mnr8sr6fhj1lxxxdlj8-cardano-node-8.1.1-linux.drv:{out}
    + /nix/store/7pb6ak9bn6qkhzixfv401wq3bn4zbx8x-cardano-node-8.1.1-linux.drv:{out}
```

In this PR I have implemented a simple heuristic that matches input derivations based on how many common inputs they have.

In the example above, the second and the third derivations wrap (with some change in the environment) a set of Haskell executables compiled with ghc-9.2.7; while the first and the fourth wrap (with the same changes in the environment) the same set of Haskell executables but this time compiled with ghc-8.10.7.

This is all confusing but the punch line is we can obtain a meaningful diff if we pair the second with the third and the first with the fourth (and recurse):
```
• The input derivation named `cardano-node-8.1.1-linux` differs
  - /nix/store/nvxxaynf8yw1r33j9jvl2nhsv2f9a59w-cardano-node-8.1.1-linux.drv:{out}
  + /nix/store/39k310w52vzx6mnr8sr6fhj1lxxxdlj8-cardano-node-8.1.1-linux.drv:{out}
  • The input derivation named `cardano-node-exe-cardano-node-x86_64-unknown-linux-musl-8.1.1` differs
    - /nix/store/cw7byxsl3ci15zv7znwxyasd4yzlljnn-cardano-node-exe-cardano-node-x86_64-unknown-linux-musl-8.1.1.drv:{out}
    + /nix/store/253vc3yqvl9sygy9yh26hgfgh8gskb8w-cardano-node-exe-cardano-node-x86_64-unknown-linux-musl-8.1.1.drv:{out}
    • The environments do not match:
...
• The input derivation named `cardano-node-8.1.1-linux` differs
  - /nix/store/cfsp91563mmi6yvz8fcvmgw1nks4dqsa-cardano-node-8.1.1-linux.drv:{out}
  + /nix/store/7pb6ak9bn6qkhzixfv401wq3bn4zbx8x-cardano-node-8.1.1-linux.drv:{out}
  • The input derivation named `cardano-cli-exe-cardano-cli-x86_64-unknown-linux-musl-8.2.0` differs
    • These two derivations have already been compared
  • The input derivation named `cardano-node-exe-cardano-node-x86_64-unknown-linux-musl-8.1.1` differs
    - /nix/store/ygszklh8w33ra1l2021npqvbhs66rha2-cardano-node-exe-cardano-node-x86_64-unknown-linux-musl-8.1.1.drv:{out}
    + /nix/store/3qv1ld64m1xa9scywzb0hbg4wjwfjgvm-cardano-node-exe-cardano-node-x86_64-unknown-linux-musl-8.1.1.drv:{out}
    • The environments do not match:
...
```

This allows me to "see through" the aggregate derivation, and pin-point the origin of the difference.

I don't expect this heuristic to work in all cases, but the user could enable it when needed with a command line flag (`--match-heuristically` ?). Note that, in its current form, the `diff` function will always perform a match and will never return `SomeDerivationsDiff` anymore.

Let me know if there is appetite to have this feature in nix-diff, so I can clean up the PR and resolve the remaining FIXMEs and TODOs before you can give it a proper review.

In case there's no interest, no worries :relaxed: no feelings other than gratitute for having made nix-diff in the first place :upside_down_face:

### CODE REVIEW

**Comment by Gabriella439** [comment]
yeah, i'd accept this!

**Comment by Gabriella439** [comment]
I just wanted to check if you wanted me to review this, yet.  Just ping me whenever you're ready for review

**Comment by andreabedini** [comment]
> I just wanted to check if you wanted me to review this, yet. Just ping me whenever you're ready for review

I think this PR is still in flux so to speak. One difect that I think I should solve is that when descending down I forget if a derivation has already been paired, so I end up pairing with another one.

Perhaps I should push to have this cleaned and merged soon, despite all the short-comings I see :)

Thanks for checking in, I will ping you when this is ready for review :relaxed:

**Comment by andreabedini** [comment]
I am sorry @Gabriella439, I don't think I will have time to continute working on this :-/

**Comment by Gabriella439** [comment]
no worries!

**Pull request closed without merging**
