### PR TITLE
Upper bounds, CI, badges

### PR DESCRIPTION
**Pull request by sorki**
in similar fashion and related to https://github.com/Gabriella439/Haskell-Nix-Derivation-Library/pull/22

`dhall.ci` was removed in favor of Garnix which was then removed and only `ci.yaml` was reintroduced (with added `nix-build`, which is now also available in `haskell-ci.dhall` as a simple [`withNix` combinator](https://github.com/sorki/github-actions-dhall/blob/main/haskell-ci.dhall#L449))

Marking as draft until we resolve `nix-derivation`.

### CODE REVIEW

**Comment by Gabriella439** [comment]
The matching PR for `nix-derivation` is merged and published to Hackage now, so this one should be good to go now.

**Comment by sorki** [comment]
I might be able to resolve the `dontCheck` as well after I extract stubbed store testing harness from `hnix-store-remote` into `hnix-store-tests`.

**Comment by sorki** [comment]
I'm scared of the `Squash and merge` button :smile_cat:

**Comment by sorki** [comment]
Think it's fine to squash all this just got me wondering if I should I create separate PRs instead for future stuff (and I should of course if the things are not quite related) and if this also automatically adds the PR ID to the commit message(s).

**Comment by Gabriella439** [comment]
I can change the repo to support other merge methods.  I'll do that right now

**Comment by sorki** [comment]
Thanks!

**Pull request merged**
